### ISSUE TITLE
Could you add Required VRAM info in the README?

### ISSUE THREAD

**Issue by treya-lin** [huggingface/distil-whisper#32]
Hi, it would be of great help if the info of required VRAM is added in the README, just as in whisper's repo where they list the vram needed for different sizes of models (https://github.com/openai/whisper#available-models-and-languages)
Thanks!

**Comment by sanchit-gandhi** [comment]
Hey @treya-lin - we did indeed consider the VRAM for these models, but found it to be highly dependent on GPU hardware, CUDA version and even PyTorch version. For example, VRAM changed considerably going between PyTorch 1.13 and 2.0 for the same models on the same hardware. Therefore, we decided to quote the parameter count as a "proxy" for VRAM usage, in order to give a fair and reliable estimate for the expected memory. 

To give you some idea of VRAM, here are **very preliminary** results I got benchmarking randomly initialised teacher/student models on a 16GB T4 GPU with PT 1.13 with no Flash Attention. I measure the time taken to generate 25 tokens and averaged over 100 examples with a batch size of 1. Feel free to use this as indicative numbers for VRAM, but I would highly advise that you measure the models on your own hardware/library versions!

![chart-2](https://github.com/huggingface/distil-whisper/assets/93869735/ec0d056c-8d31-4d4e-8800-baba6a770124)

**Comment by treya-lin** [comment]
> Hey @treya-lin - we did indeed consider the VRAM for these models, but found it to be highly dependent on GPU hardware, CUDA version and even PyTorch version. For example, VRAM changed considerably going between PyTorch 1.13 and 2.0 for the same models on the same hardware. Therefore, we decided to quote the parameter count as a "proxy" for VRAM usage, in order to give a fair and reliable estimate for the expected memory.
> 
> To give you some idea of VRAM, here are **very preliminary** results I got benchmarking **randomly initialised** teacher/student models on a 16GB T4 GPU with PT 1.13 with no Flash Attention. Here, I measured the time taken to generate 25 tokens with a batch size of 1, and then averaged over 100 examples. Feel free to use this as indicative numbers for VRAM, but I would highly advise that you measure the Whisper/Distil-Whisper models on your own hardware/library versions!
> 
> ![chart-2](https://user-images.githubusercontent.com/93869735/282488856-ec0d056c-8d31-4d4e-8800-baba6a770124.png)

Hi thanks for the details. Very helpful information, thanks! I will take a look at how it works in my environment.
